### ISSUE TITLE
Hi, this plugin doesn't work now?

### ISSUE THREAD

**Issue by LemonPAKA** [MoeJoe111/RoundRestore#1]
I put it on plugin folder and input sm plugins list in console...It got <ERROR> restoreround, I dont know why(my server using warmod)

**Comment by mrc4tt** [comment]
@MoritzLoewenstein 

Maybe there is a fix?

**Comment by MoritzLoewenstein** [comment]
I will look into it tomorrow, should be fast fix.

**Comment by MoritzLoewenstein** [comment]
Fixed, also simplified Menu a little bit and uploaded new smx in releases
