### ISSUE TITLE
sm_restorelast restores all rounds instead of just the last round

### ISSUE THREAD

**Issue by crashzk** [MoeJoe111/RoundRestore#4]
`!restorelast` restores all rounds instead of just the last round.

**sm plugins list:**
```
[SM] Listing 43 plugins:
  01 "Client Preferences" (1.10.0.6492) by AlliedModders LLC
  02 "CS:GO PugSetup: damage printer" (2.0.5) by splewis
  03 "Basic Info Triggers" (1.10.0.6492) by AlliedModders LLC
  04 "Admin Menu" (1.10.0.6492) by AlliedModders LLC
  05 "[CS:GO] Fake Competitive Ranks/Coins/Profile" (1.2.1) by Laam4
  06 "Basic Votes" (1.10.0.6492) by AlliedModders LLC
  07 "[CS:GO] Music Kits [Menu]" (1.7.3) by iEx Edited by Kento
  08 "[CS:GO] Bot Quota Fix" (FINAL) by TheWho
  09 "ServerAdvertisements3" (3.1.3) by ESK0
  10 "CS:GO PugSetup: hostname setter" (2.0.5) by splewis
  11 "CS:GO Max team size" (1.0.0) by splewis
  12 "CS:GO PugSetup: autokicker" (2.0.5) by splewis
  13 "Fun Commands" (1.10.0.6492) by AlliedModders LLC
  14 "[ ZK Servidores ] - Block Commands" (1.0) by By: Geison TecnoHard - Edited: crashzk
  15 "CS:GO PugSetup" (2.0.5) by splewis
  16 "CS:GO PugSetup: team locker" (2.0.5) by splewis
  17 "Basic Commands" (1.10.0.6492) by AlliedModders LLC
  18 "AFK Manager" (4.3.0) by Rothgar
  19 "SM Franug CS:GO Agents Chooser" (1.1.2) by Franc1sco franug
  20 "Steam Works Group Manager" (1.7) by Someone
  21 "TecnoHard AllChat Control" (1.2) by AbNeR @CSB
  22 "Anti-Flood" (1.10.0.6492) by AlliedModders LLC
  23 "Basic Ban Commands" (1.10.0.6492) by AlliedModders LLC
  24 "Admin File Reader" (1.10.0.6492) by AlliedModders LLC
  25 "hextags" (1.45) by Hexah
  26 "[ ZK Servidores ] - Automatic Response" (1.1) by Plock - Edited: crashzk
  27 "Weapons & Knives" (1.7.0) by kgns | oyunhost.net
  28 "CS:GO PugSetup: write team money to chat" (2.0.5) by Versatile_BFG/jkroepke
  29 "Basic Comm Control" (1.10.0.6492) by AlliedModders LLC
  30 "Gloves" (1.0.4) by kgns | oyunhost.net
  31 "[Levels Ranks] Core" (v3.0 SR1) by RoadSide Romeo & Wend4r
  32 "Basic Chat" (1.10.0.6492) by AlliedModders LLC
  33 "[ ZK Servidores™ ] CS:GO Friendly Fire" (3.1) by Dk--, crashzk
  34 "[SWGM] Command Listener" (1.1) by Someone
  35 "Round Restore" (0.9) by Moritz Loewenstein
  36 "Sound Commands" (1.10.0.6492) by AlliedModders LLC
  37 "Player Commands" (1.10.0.6492) by AlliedModders LLC
  38 "Admin Help" (1.10.0.6492) by AlliedModders LLC
  39 "Nextmap" (1.10.0.6492) by AlliedModders LLC
  40 "Reserved Slots" (1.10.0.6492) by AlliedModders LLC
  41 "Fun Votes" (1.10.0.6492) by AlliedModders LLC
  42 "Chat-Processor" (2.2.0) by Keith Warren (Drixevel)
  43 "HANSE Reserved Slots" (2.0) by red!
```
 **SourceMod Version Information:**
```
    SourceMod Version: 1.10.0.6492
    SourcePawn Engine: 1.10.0.6492, jit-x86 (build 1.10.0.6492)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Jul 24 2020 20:07:18
    Built from: https://github.com/alliedmodders/sourcemod/commit/250886f
    Build ID: 6492:250886f
    http://www.sourcemod.net/
```
**Round Restore Version:** "Round Restore" (0.9) by Moritz Loewenstein
**PUGSetup Version:** "CS:GO PugSetup" (2.0.5) by splewis

**mp_backup_round_file_pattern:** `"%prefix%_round%round%.txt"`

**Comment by crashzk** [comment]
Same thing with the `!restore` command no matter which round you choose to restore it returns it restores all rounds.

**Comment by MoritzLoewenstein** [comment]
Is the title in the menu for restoring the last round correct? ("Restore round x?")  
Currently it just loads round after round from 0 to 30 or how does it load "all" rounds?

**Comment by MoritzLoewenstein** [comment]
ping @crashzk

**Comment by crashzk** [comment]
Sorry, I'm going to check it out, I didn't notice it. I will get this information and I'll be back as soon as possible.

**Comment by lugaamn** [comment]
To restore, go to the first round 0. For example, I play in the 30th generation, and when I want to go to the 5th, 10th, 8th, etc., I go to the 0th generation.

//MY Server BACKUP

"mp_backup_restore_list_files"  game                                             - Lists recent backup round files matching the prefix, most recent files first, ac
"mp_backup_restore_load_autopause" = "1" game                                    - Whether to automatically pause the match after restoring round data from backup
"mp_backup_restore_load_file"  game                                              - Loads player cash, KDA, scores and team scores; resets to the next round after t
"mp_backup_round_auto" = "1" game                                                - If enabled will keep in-memory backups to handle reconnecting players even if th
"mp_backup_round_file" = "backup" game                                           - If set then server will save all played rounds information to files filename_dat
"mp_backup_round_file_last" = "" game                                            - Every time a backup file is written the value of this convar gets updated to hol
"mp_backup_round_file_pattern" = "%prefix%_round%round%.txt" game                - If set then server will save all played rounds information to files named by thi
"sv_vote_issue_loadbackup_allowed" = "1" game notify replicated                  - Can people hold votes to load match from backup?

**Comment by lugaamn** [comment]
![plugin no error](https://user-images.githubusercontent.com/52530000/110190189-08d27280-7e5d-11eb-9909-53ca23cac769.PNG)
![server cfg backup](https://user-images.githubusercontent.com/52530000/110190195-0ec85380-7e5d-11eb-89e5-676aa48e9249.PNG)
![sm version](https://user-images.githubusercontent.com/52530000/110190197-112aad80-7e5d-11eb-9ae4-ff90fb768820.PNG)
![meta version](https://user-images.githubusercontent.com/52530000/110190201-17b92500-7e5d-11eb-9a6b-1d954b64441a.PNG)

Previous rounds are not restored. Only the first round is restored

**Comment by MoritzLoewenstein** [comment]
Hi, can you send a screenshot of ingame chat  / or recording how this looks like when it happens?

**Comment by lugaamn** [comment]
![backup txt](https://user-images.githubusercontent.com/52530000/110205317-562cff00-7eb2-11eb-9050-4a3ee42c7cca.JPG)
![de_mirage0001](https://user-images.githubusercontent.com/52530000/110205321-575e2c00-7eb2-11eb-81c6-251146d16d0d.jpg)
![de_mirage0002](https://user-images.githubusercontent.com/52530000/110205322-57f6c280-7eb2-11eb-8249-bdfc9a74522e.jpg)
![de_mirage0003](https://user-images.githubusercontent.com/52530000/110205323-588f5900-7eb2-11eb-9399-925afdaa8b14.jpg)
![de_mirage0004](https://user-images.githubusercontent.com/52530000/110205324-588f5900-7eb2-11eb-93a7-04f0663ad195.jpg)
![de_mirage0005](https://user-images.githubusercontent.com/52530000/110205327-5927ef80-7eb2-11eb-854a-7c7c835891e7.jpg)
![de_mirage0006](https://user-images.githubusercontent.com/52530000/110205329-59c08600-7eb2-11eb-84cf-17c6a01776b9.jpg)
![de_mirage0007](https://user-images.githubusercontent.com/52530000/110205330-5a591c80-7eb2-11eb-9524-0cf3c0eb7f6d.jpg)
![de_mirage0008](https://user-images.githubusercontent.com/52530000/110205331-5af1b300-7eb2-11eb-80bc-ff2fcff1570f.jpg)
![de_mirage0009](https://user-images.githubusercontent.com/52530000/110205332-5af1b300-7eb2-11eb-9c1b-4452d44f8f37.jpg)
![de_mirage0011](https://user-images.githubusercontent.com/52530000/110205333-5b8a4980-7eb2-11eb-83a5-eb8c41a11e46.jpg)
![de_mirage0012](https://user-images.githubusercontent.com/52530000/110205334-5c22e000-7eb2-11eb-857f-d092503a1606.jpg)
![de_mirage0013](https://user-images.githubusercontent.com/52530000/110205335-5c22e000-7eb2-11eb-9efa-e3caeaf40425.jpg)


always run to round00.txt

**Comment by MoritzLoewenstein** [comment]
Thank you, can you check if this works? Just copy RoundRestore.smx to your server.
[RoundRestore](https://github.com/MoritzLoewenstein/RoundRestore/files/6096967/RoundRestore.zip)

**Comment by lugaamn** [comment]
Yes, it is working properly now. Thanks, we can't go to zero, but that's not a problem. All you have to do is restart the game.

There is also one problem, what if the periods exceed 30? Is it possible to restore? I haven't tried it yet. Thanks anyway.

**Comment by MoritzLoewenstein** [comment]
When you go on "previous rounds" it justs shows "Round 1, 2, 3 ..." instead of "Round 0, 1, 2, ..." ?
Currently it will only show rounds until 30, maybe i can change that.
